/**
 * Pins every `androidx.media3` artifact to the version expo-video and expo-audio
 * were compiled against.
 *
 * Without this the app dies on the very first frame:
 *
 *   java.lang.AbstractMethodError: abstract method
 *   "androidx.media3.exoplayer.upstream.Allocator
 *    androidx.media3.exoplayer.LoadControl.getAllocator(
 *      androidx.media3.exoplayer.analytics.PlayerId)"
 *   on receiver java.lang.Class<expo.modules.video.player.VideoPlayerLoadControl>
 *
 * Why it happens: expo-video and expo-audio both hardcode
 * `def androidxMedia3Version = "1.8.0"` in their own android/build.gradle.
 * react-native-vision-camera pulls in androidx.camera, and
 * `androidx.camera:camera-video:1.7.0-alpha02` declares runtime deps on
 * `androidx.media3:media3-muxer:1.9.0` and `androidx.media3:media3-container:1.9.0`.
 * Gradle's default conflict resolution takes the newest version across the whole
 * group, so debugRuntimeClasspath ends up on media3 1.9.0. `LoadControl` grew a
 * `getAllocator(PlayerId)` overload in 1.9.0, so expo-video's
 * `VideoPlayerLoadControl` — compiled against the 1.8.0 interface — no longer
 * implements it, and the class fails to load.
 *
 * The fix has to live here rather than in android/app/build.gradle because
 * android/ is gitignored and regenerated by `expo prebuild`, so any edit there
 * is thrown away on the next prebuild.
 *
 * Revisit when expo-video/expo-audio bump to media3 1.9.0 (check
 * `node_modules/expo-video/android/build.gradle`). At that point delete this
 * plugin instead of raising MEDIA3_VERSION, so the two stay in lockstep on their
 * own. Downgrading media3-muxer/media3-container from 1.9.0 to 1.8.0 is the cost
 * of the pin — CameraX video recording rides on those.
 */
const { withProjectBuildGradle } = require('expo/config-plugins');

const MEDIA3_VERSION = '1.8.0';
const START = '// @generated withMedia3Pin begin';
const END = '// @generated withMedia3Pin end';

const block = `${START}
// See plugins/withMedia3Pin.js. expo-video/expo-audio are built against media3
// ${MEDIA3_VERSION}; androidx.camera:camera-video asks for 1.9.0 and Gradle takes the
// newest, which breaks VideoPlayerLoadControl with AbstractMethodError at startup.
allprojects {
  configurations.all {
    resolutionStrategy.eachDependency { details ->
      if (details.requested.group == 'androidx.media3') {
        details.useVersion '${MEDIA3_VERSION}'
        details.because 'expo-video and expo-audio are compiled against media3 ${MEDIA3_VERSION}'
      }
    }
  }
}
${END}`;

function stripExisting(contents) {
  const from = contents.indexOf(START);
  if (from === -1) return contents;
  const to = contents.indexOf(END);
  if (to === -1) return contents;
  return contents.slice(0, from) + contents.slice(to + END.length);
}

module.exports = function withMedia3Pin(config) {
  return withProjectBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error(
        `withMedia3Pin only supports the Groovy android/build.gradle, got ${cfg.modResults.language}`
      );
    }
    cfg.modResults.contents = `${stripExisting(cfg.modResults.contents).trimEnd()}\n\n${block}\n`;
    return cfg;
  });
};
