/**
 * Shared food catalog + diet domain types for the macro tracker.
 *
 * CANONICAL MODEL (matches USDA / Open Food Facts / FatSecret / Cronometer and the
 * DB after migration 0065): each food stores its nutrients ONCE per 100 base-units
 * (`base_unit` = 'g' for solids, 'ml' for liquids). Portions are a SEPARATE list
 * (`servings`): each is a label mapped to a weight in the food's base unit, e.g.
 * egg -> ["100 g", "1 large egg" = 50 g], dal -> ["1 katori" = 150 g, "100 g"].
 * At log time the user picks a serving (or a universal unit) and a quantity; we
 * resolve to base-unit amount, then macros = per-100 * amount / 100.
 *
 * Household/portion units (katori, roti, scoop, 1 egg) are per-food gram weights
 * (their weight is intrinsic to the food). Universal mass/volume units
 * (g/kg/oz/lb, ml/l/cup/tbsp/tsp) are pure math in lib/units.ts.
 *
 * FOOD_LIBRARY below is a small hand-curated set of Indian staples that USDA lacks
 * (paneer, dal, roti, idli, dosa, whey). The broad catalog (USDA per-100 + portions
 * from food_portion.csv, Open Food Facts, computed Indian dishes) is generated by
 * scripts/diet-catalog and merged at runtime. Nutrient numbers are facts, authored
 * by us, so no licensing taint. See .planning/diet-tracking-plan.md.
 */

import { MASS_UNITS, VOLUME_UNITS, massToGrams, volumeToMl } from './units';

// ── Enums (mirror the DB CHECK constraints in migrations 0046 + 0065) ────────

export type FoodCategory =
  | 'protein' | 'legume' | 'dairy' | 'grain' | 'vegetable' | 'fruit' | 'fat_oil'
  | 'nuts_seeds' | 'prepared_dish' | 'snack' | 'beverage' | 'sweet' | 'supplement'
  | 'condiment' | 'other';

export const FOOD_CATEGORIES: FoodCategory[] = [
  'protein', 'legume', 'dairy', 'grain', 'vegetable', 'fruit', 'fat_oil',
  'nuts_seeds', 'prepared_dish', 'snack', 'beverage', 'sweet', 'supplement',
  'condiment', 'other',
];
export const DEFAULT_FOOD_CATEGORY: FoodCategory = 'other';

export function foodCategoryOf(v: string | null | undefined): FoodCategory {
  return v && (FOOD_CATEGORIES as string[]).includes(v) ? (v as FoodCategory) : DEFAULT_FOOD_CATEGORY;
}

/** Nutrient basis. 'g' for solids (per 100 g), 'ml' for liquids (per 100 ml). */
export type BaseUnit = 'g' | 'ml';
export const DEFAULT_BASE_UNIT: BaseUnit = 'g';

/** Provenance. Open Food Facts rows ('off') stay segregated + attributed (ODbL). */
export type FoodSource = 'usda' | 'off' | 'curated' | 'user';
export const DEFAULT_FOOD_SOURCE: FoodSource = 'curated';

// ── Nutrients (values are PER 100 base-units on a food; a snapshot on an entry) ──

export interface Nutrients {
  kcal: number;
  protein_g: number;
  carb_g: number;
  fat_g: number;
  /** Extended (good-to-have). Optional on definitions; null = genuinely unknown
   *  (distinct from a real 0), preserved through logging (migrations 0066/0069). */
  fiber_g?: number | null;
  sugar_g?: number | null;
  sat_fat_g?: number | null;
  sodium_mg?: number | null;
}

/** Nutrients with every field resolved to a plain number — unknown extended
 *  values are coerced to 0 for display/math (nutrientsForAmount, sumNutrients). */
export type ResolvedNutrients = { [K in keyof Required<Nutrients>]: number };

export const ZERO_NUTRIENTS: ResolvedNutrients = {
  kcal: 0, protein_g: 0, carb_g: 0, fat_g: 0,
  fiber_g: 0, sugar_g: 0, sat_fat_g: 0, sodium_mg: 0,
};

/** A named portion option on a food. `grams` is the weight in the food's base unit. */
export interface FoodServing {
  label: string;       // "100 g", "1 katori", "1 scoop"
  grams: number;       // weight in base_unit (g or ml)
  is_default?: boolean;
  source?: FoodSource;
}

// ── Entity shapes ────────────────────────────────────────────────────────────

/** A catalog food. Nutrient fields are PER 100 base-units. */
export interface FoodDef extends Nutrients {
  name: string;
  food_category: FoodCategory;
  base_unit: BaseUnit;
  servings: FoodServing[];
  density_g_per_ml?: number; // only used to cross mass<->volume for this food
  brand?: string;
  source?: FoodSource;
}

/** A `foods` table row (FoodDef + server/identity fields). */
export interface Food extends FoodDef {
  id: string;
  barcode?: string | null;
  image_url?: string | null;
  created_by?: string | null; // null = global
  micros?: Record<string, number> | null; // deferred open-ended tail (jsonb)
  sources?: FoodSource[] | null; // every dataset that contributed (provenance + ODbL)
}

export type MealType = 'breakfast' | 'lunch' | 'dinner' | 'snack';
export const MEAL_TYPES: MealType[] = ['breakfast', 'lunch', 'dinner', 'snack'];

/** A logged meal (analog of a `workouts` row). */
export interface Meal {
  id: string;
  user_id?: string;
  logged_at: string; // ISO; the real event time, captured at log, not sync
  meal_type: MealType;
  note?: string | null;
  client_id?: string | null;
  entries?: MealEntry[];
}

/**
 * One food within a meal. DENORMALIZED (food_name + nutrient snapshot + grams_logged)
 * so history is immutable, the log renders without a join, and offline rows survive
 * even when food_id / serving_id are null.
 */
export interface MealEntry {
  id: string;
  meal_id: string;
  food_id?: string | null;
  serving_id?: string | null;
  food_name: string;
  /** How many of `serving_unit` the user logged (e.g. 2 katori). */
  quantity: number;
  /** Display label of the chosen portion/unit ("1 katori", "g", "100 g"). */
  serving_unit: string;
  /** The resolved base-unit amount consumed (drives the macro snapshot). */
  grams_logged?: number;
  kcal: number;
  protein_g: number;
  carb_g: number;
  fat_g: number;
  fiber_g?: number | null;
  sugar_g?: number | null;
  sat_fat_g?: number | null;
  sodium_mg?: number | null;
  position: number;
}

/** Daily calorie/macro goals (nullable columns on user_profiles, migration 0048). */
export interface NutritionTargets {
  daily_calorie_target?: number | null;
  protein_target_g?: number | null;
  carb_target_g?: number | null;
  fat_target_g?: number | null;
}

// ── Nutrient maths ───────────────────────────────────────────────────────────

/** Nutrients for `amount` base-units of a food (per-100 scaled). Pure; round in UI. */
export function nutrientsForAmount(food: Nutrients, amount: number): ResolvedNutrients {
  const f = amount / 100;
  return {
    kcal: food.kcal * f,
    protein_g: food.protein_g * f,
    carb_g: food.carb_g * f,
    fat_g: food.fat_g * f,
    fiber_g: (food.fiber_g ?? 0) * f,
    sugar_g: (food.sugar_g ?? 0) * f,
    sat_fat_g: (food.sat_fat_g ?? 0) * f,
    sodium_mg: (food.sodium_mg ?? 0) * f,
  };
}

/** Sum nutrient rows (e.g. a meal, or a day). */
export function sumNutrients(rows: Nutrients[]): ResolvedNutrients {
  return rows.reduce<ResolvedNutrients>((a, m) => ({
    kcal: a.kcal + m.kcal,
    protein_g: a.protein_g + m.protein_g,
    carb_g: a.carb_g + m.carb_g,
    fat_g: a.fat_g + m.fat_g,
    fiber_g: a.fiber_g + (m.fiber_g ?? 0),
    sugar_g: a.sugar_g + (m.sugar_g ?? 0),
    sat_fat_g: a.sat_fat_g + (m.sat_fat_g ?? 0),
    sodium_mg: a.sodium_mg + (m.sodium_mg ?? 0),
  }), { ...ZERO_NUTRIENTS });
}

/** The pre-selected serving for the picker (explicit default, else first, else 100). */
export function defaultServing(food: FoodDef): FoodServing {
  return (
    food.servings.find((s) => s.is_default) ??
    food.servings[0] ??
    { label: `100 ${food.base_unit}`, grams: 100 }
  );
}

/**
 * Resolve a logged (unit, quantity) to the food's base-unit amount (g or ml).
 * `unit` is either a serving label on this food, or a universal mass/volume unit.
 * Returns null for an unknown unit.
 */
export function resolveBaseAmount(food: FoodDef, unit: string, quantity: number): number | null {
  const serving = food.servings.find((s) => s.label.toLowerCase() === unit.toLowerCase());
  if (serving) return serving.grams * quantity;

  const density = food.density_g_per_ml ?? 1;
  if (unit in MASS_UNITS) {
    const grams = massToGrams(quantity, unit);
    return food.base_unit === 'g' ? grams : grams / density; // ml for an ml-base food
  }
  if (unit in VOLUME_UNITS) {
    const ml = volumeToMl(quantity, unit);
    return food.base_unit === 'ml' ? ml : ml * density; // grams for a g-base food
  }
  return null;
}

// ── Search ───────────────────────────────────────────────────────────────────

export function searchFoods(query: string, library = FOOD_LIBRARY): FoodDef[] {
  const q = query.toLowerCase().trim();
  if (!q) return library;
  return library.filter(
    (f) =>
      f.name.toLowerCase().includes(q) ||
      f.food_category.toLowerCase().includes(q) ||
      (f.brand ? f.brand.toLowerCase().includes(q) : false),
  );
}

// ── Starter library: Indian staples USDA lacks (per 100 base-units) ──────────
// The broad catalog comes from scripts/diet-catalog (USDA + OFF + computed dishes).

const S = (label: string, grams: number, is_default = false): FoodServing => ({
  label, grams, is_default, source: 'curated',
});

export const FOOD_LIBRARY: FoodDef[] = [
  {
    name: 'Paneer', food_category: 'dairy', base_unit: 'g',
    kcal: 265, protein_g: 18, carb_g: 1.2, fat_g: 20, fiber_g: 0, sugar_g: 1.2, sat_fat_g: 12, sodium_mg: 18,
    servings: [S('100 g', 100, true), S('1 cube', 25)], source: 'curated',
  },
  {
    name: 'Roti / Chapati', food_category: 'grain', base_unit: 'g',
    kcal: 300, protein_g: 7.5, carb_g: 45, fat_g: 9, fiber_g: 4.9, sugar_g: 0.8, sat_fat_g: 1.5, sodium_mg: 190,
    servings: [S('1 roti', 40, true), S('100 g', 100)], source: 'curated',
  },
  {
    name: 'Toor Dal (cooked)', food_category: 'legume', base_unit: 'g',
    kcal: 77, protein_g: 4.7, carb_g: 12, fat_g: 1, fiber_g: 3, sugar_g: 0.5, sat_fat_g: 0.2, sodium_mg: 5,
    servings: [S('1 katori', 150, true), S('100 g', 100)], source: 'curated',
  },
  {
    name: 'Moong Dal (cooked)', food_category: 'legume', base_unit: 'g',
    kcal: 70, protein_g: 4.7, carb_g: 12.7, fat_g: 0.3, fiber_g: 2, sugar_g: 0.5, sat_fat_g: 0.1, sodium_mg: 3,
    servings: [S('1 katori', 150, true), S('100 g', 100)], source: 'curated',
  },
  {
    name: 'Idli', food_category: 'prepared_dish', base_unit: 'g',
    kcal: 145, protein_g: 5, carb_g: 30, fat_g: 1, fiber_g: 1, sugar_g: 0.5, sat_fat_g: 0.2, sodium_mg: 200,
    servings: [S('1 idli', 40, true), S('100 g', 100)], source: 'curated',
  },
  {
    name: 'Plain Dosa', food_category: 'prepared_dish', base_unit: 'g',
    kcal: 166, protein_g: 3.4, carb_g: 22.5, fat_g: 6.3, fiber_g: 1.2, sugar_g: 0.5, sat_fat_g: 1, sodium_mg: 250,
    servings: [S('1 dosa', 80, true), S('100 g', 100)], source: 'curated',
  },
  {
    name: 'Whey Protein', food_category: 'supplement', base_unit: 'g',
    kcal: 375, protein_g: 75, carb_g: 9, fat_g: 4.7, fiber_g: 0, sugar_g: 6, sat_fat_g: 2, sodium_mg: 300,
    servings: [S('1 scoop', 32, true), S('100 g', 100)], source: 'curated',
  },
  {
    name: 'Curd / Dahi', food_category: 'dairy', base_unit: 'g',
    kcal: 60, protein_g: 3.1, carb_g: 4.7, fat_g: 3.3, fiber_g: 0, sugar_g: 4.7, sat_fat_g: 2, sodium_mg: 46,
    servings: [S('1 katori', 150, true), S('100 g', 100)], source: 'curated',
  },
  {
    name: 'Toned Milk', food_category: 'dairy', base_unit: 'ml',
    kcal: 48, protein_g: 3.2, carb_g: 4.8, fat_g: 1.6, fiber_g: 0, sugar_g: 4.8, sat_fat_g: 1, sodium_mg: 44,
    density_g_per_ml: 1.03,
    servings: [S('1 glass', 250, true), S('100 ml', 100)], source: 'curated',
  },
  {
    name: 'Soya Chunks (dry)', food_category: 'protein', base_unit: 'g',
    kcal: 345, protein_g: 52, carb_g: 33, fat_g: 0.5, fiber_g: 13, sugar_g: 2, sat_fat_g: 0.1, sodium_mg: 2,
    servings: [S('100 g', 100, true), S('1 cup', 40)], source: 'curated',
  },
];
