-- GENERATED by scripts/diet-catalog/build.ts — do not edit by hand.
-- Apply as SERVICE ROLE so created_by stays null (global rows). Idempotent via
-- the uq_foods_name_global index. Sourcing/license: scripts/diet-catalog/README.md.
insert into public.foods
  (name, food_category, serving_unit, serving_size, kcal, protein_g, carb_g, fat_g, brand, barcode, source)
values
  ('Almonds','nuts_seeds','g',100,598,21,21,52.5,null,null,'usda'),
  ('Apple','fruit','g',100,52,0.3,13.8,0.2,null,null,'usda'),
  ('Banana','fruit','g',100,89,1.1,22.8,0.3,null,null,'usda'),
  ('Broccoli (raw)','vegetable','g',100,34,2.8,6.6,0.4,null,null,'usda'),
  ('Brown Rice (cooked)','grain','g',100,123,2.7,25.6,1,null,null,'usda'),
  ('Butter','fat_oil','g',100,717,0.9,0.1,81.1,null,null,'usda'),
  ('Cheddar Cheese','dairy','g',100,410,24.3,2.1,33.8,null,null,'usda'),
  ('Chicken Biryani','prepared_dish','bowl',1,501,33.1,53.1,15.8,null,null,'curated'),
  ('Chicken Breast (cooked)','protein','g',100,165,31,0,3.6,null,null,'usda'),
  ('Chicken Thigh (cooked)','protein','g',100,179,24.8,0,8.2,null,null,'usda'),
  ('Chickpeas (cooked)','legume','g',100,164,8.9,27.4,2.6,null,null,'usda'),
  ('Cottage Cheese (lowfat)','dairy','g',100,81,10.5,4.8,2.3,null,null,'usda'),
  ('Dal Tadka','prepared_dish','bowl',1,265,11.2,32.6,8.7,null,null,'curated'),
  ('Egg (whole, raw)','protein','g',100,143,12.6,0.7,9.5,null,null,'usda'),
  ('Greek Yogurt (plain, nonfat)','dairy','g',100,59,10.2,3.6,0.4,null,null,'usda'),
  ('Kidney Beans (cooked)','legume','g',100,127,8.7,22.8,0.5,null,null,'usda'),
  ('Lentils (cooked)','legume','g',100,116,9,20.1,0.4,null,null,'usda'),
  ('Oats (dry)','grain','g',100,379,13.2,67.7,6.5,null,null,'usda'),
  ('Olive Oil','fat_oil','g',100,884,0,0,100,null,null,'usda'),
  ('Paneer Butter Masala','prepared_dish','bowl',1,355,16.1,6.9,29,null,null,'curated'),
  ('Peanut Butter','nuts_seeds','g',100,598,22.2,22.3,51.4,null,null,'usda'),
  ('Peanuts','nuts_seeds','g',100,587,24.4,21.3,49.7,null,null,'usda'),
  ('Potato (boiled)','vegetable','g',100,87,1.9,20.1,0.1,null,null,'usda'),
  ('Rajma Chawal','prepared_dish','bowl',1,433,15,71.6,9.1,null,null,'curated'),
  ('Salmon (cooked)','protein','g',100,206,22.1,0,12.4,null,null,'usda'),
  ('Shrimp (cooked)','protein','g',100,99,24,0.2,0.3,null,null,'usda'),
  ('Spinach (raw)','vegetable','g',100,23,2.9,3.6,0.4,null,null,'usda'),
  ('Sweet Potato (cooked)','vegetable','g',100,90,2,20.7,0.2,null,null,'usda'),
  ('Tofu (firm)','protein','g',100,78,9,2.9,4.2,null,null,'usda'),
  ('Tuna (canned in water)','protein','g',100,86,19.4,0,1,null,null,'usda'),
  ('Walnuts','nuts_seeds','g',100,654,15.2,13.7,65.2,null,null,'usda'),
  ('White Rice (cooked)','grain','g',100,130,2.7,28.2,0.3,null,null,'usda'),
  ('Whole Milk','dairy','g',100,61,3.2,4.8,3.3,null,null,'usda'),
  ('Whole Wheat Bread','grain','g',100,252,12.5,42.7,3.5,null,null,'usda'),
  ('Whole Wheat Flour (atta)','grain','g',100,332,9.6,74.5,2,null,null,'usda')
on conflict do nothing;
