-- GENERATED by scripts/diet-catalog/build.ts — do not edit by hand.
-- Apply as SERVICE ROLE so created_by stays null (global rows). Idempotent via the
-- uq_foods_name_global index. Sourcing/license: scripts/diet-catalog/README.md.
with f as (
  insert into public.foods
    (name, food_category, base_unit, kcal, protein_g, carb_g, fat_g, fiber_g, sugar_g, sat_fat_g, sodium_mg, brand, barcode, source)
  values ('Almonds','nuts_seeds','g',598,21,21,52.5,10.9,4.9,4.1,3,null,null,'usda')
  on conflict do nothing returning id
)
insert into public.food_servings (food_id, label, grams, is_default, source, seq)
select f.id, v.label, v.grams, v.is_default, v.source, v.seq
from f cross join (values ('1 cup whole kernels',138,true,'usda',1), ('1 oz (22 whole kernels)',28.35,false,'usda',2), ('100 g',100,false,'usda',999)) as v(label, grams, is_default, source, seq);

with f as (
  insert into public.foods
    (name, food_category, base_unit, kcal, protein_g, carb_g, fat_g, fiber_g, sugar_g, sat_fat_g, sodium_mg, brand, barcode, source)
  values ('Apple','fruit','g',52,0.3,13.8,0.2,2.4,10.4,0,1,null,null,'usda')
  on conflict do nothing returning id
)
insert into public.food_servings (food_id, label, grams, is_default, source, seq)
select f.id, v.label, v.grams, v.is_default, v.source, v.seq
from f cross join (values ('1 cup, quartered or chopped',125,true,'usda',1), ('1 cup slices',109,false,'usda',2), ('1 large (3-1/4" dia)',223,false,'usda',3), ('1 medium (3" dia)',182,false,'usda',4), ('1 small (2-3/4" dia)',149,false,'usda',5), ('1 extra small (2-1/2" dia)',101,false,'usda',6), ('1 NLEA serving',242,false,'usda',7), ('100 g',100,false,'usda',999)) as v(label, grams, is_default, source, seq);

with f as (
  insert into public.foods
    (name, food_category, base_unit, kcal, protein_g, carb_g, fat_g, fiber_g, sugar_g, sat_fat_g, sodium_mg, brand, barcode, source)
  values ('Banana','fruit','g',89,1.1,22.8,0.3,2.6,12.2,0.1,1,null,null,'usda')
  on conflict do nothing returning id
)
insert into public.food_servings (food_id, label, grams, is_default, source, seq)
select f.id, v.label, v.grams, v.is_default, v.source, v.seq
from f cross join (values ('1 cup, mashed',225,true,'usda',1), ('1 cup, sliced',150,false,'usda',2), ('1 extra small (less than 6" long)',81,false,'usda',3), ('1 small (6" to 6-7/8" long)',101,false,'usda',4), ('1 medium (7" to 7-7/8" long)',118,false,'usda',5), ('1 large (8" to 8-7/8" long)',136,false,'usda',6), ('1 extra large (9" or longer)',152,false,'usda',7), ('1 NLEA serving',126,false,'usda',8), ('100 g',100,false,'usda',999)) as v(label, grams, is_default, source, seq);

with f as (
  insert into public.foods
    (name, food_category, base_unit, kcal, protein_g, carb_g, fat_g, fiber_g, sugar_g, sat_fat_g, sodium_mg, brand, barcode, source)
  values ('Broccoli (raw)','vegetable','g',34,2.8,6.6,0.4,2.6,1.7,0.1,33,null,null,'usda')
  on conflict do nothing returning id
)
insert into public.food_servings (food_id, label, grams, is_default, source, seq)
select f.id, v.label, v.grams, v.is_default, v.source, v.seq
from f cross join (values ('1 cup chopped',91,true,'usda',1), ('1 bunch',608,false,'usda',2), ('1 spear (about 5" long)',31,false,'usda',3), ('1 stalk',151,false,'usda',4), ('0.5 cup, chopped or diced',44,false,'usda',5), ('1 NLEA serving',148,false,'usda',6), ('100 g',100,false,'usda',999)) as v(label, grams, is_default, source, seq);

with f as (
  insert into public.foods
    (name, food_category, base_unit, kcal, protein_g, carb_g, fat_g, fiber_g, sugar_g, sat_fat_g, sodium_mg, brand, barcode, source)
  values ('Brown Rice (cooked)','grain','g',123,2.7,25.6,1,1.6,0.2,0.3,4,null,null,'usda')
  on conflict do nothing returning id
)
insert into public.food_servings (food_id, label, grams, is_default, source, seq)
select f.id, v.label, v.grams, v.is_default, v.source, v.seq
from f cross join (values ('1 cup',202,true,'usda',1), ('100 g',100,false,'usda',999)) as v(label, grams, is_default, source, seq);

with f as (
  insert into public.foods
    (name, food_category, base_unit, kcal, protein_g, carb_g, fat_g, fiber_g, sugar_g, sat_fat_g, sodium_mg, brand, barcode, source)
  values ('Butter','fat_oil','g',717,0.9,0.1,81.1,0,0.1,51.4,643,null,null,'usda')
  on conflict do nothing returning id
)
insert into public.food_servings (food_id, label, grams, is_default, source, seq)
select f.id, v.label, v.grams, v.is_default, v.source, v.seq
from f cross join (values ('1 pat (1" sq, 1/3" high)',5,true,'usda',1), ('1 tbsp',14.2,false,'usda',2), ('1 cup',227,false,'usda',3), ('1 stick',113,false,'usda',4), ('100 g',100,false,'usda',999)) as v(label, grams, is_default, source, seq);

with f as (
  insert into public.foods
    (name, food_category, base_unit, kcal, protein_g, carb_g, fat_g, fiber_g, sugar_g, sat_fat_g, sodium_mg, brand, barcode, source)
  values ('Cheddar Cheese','dairy','g',410,24.3,2.1,33.8,0,0.3,19.4,644,null,null,'usda')
  on conflict do nothing returning id
)
insert into public.food_servings (food_id, label, grams, is_default, source, seq)
select f.id, v.label, v.grams, v.is_default, v.source, v.seq
from f cross join (values ('1 slice (2/3 oz)',19,true,'usda',1), ('1 slice (3/4 oz)',21,false,'usda',2), ('1 slice (1 oz)',28,false,'usda',3), ('100 g',100,false,'usda',999)) as v(label, grams, is_default, source, seq);

with f as (
  insert into public.foods
    (name, food_category, base_unit, kcal, protein_g, carb_g, fat_g, fiber_g, sugar_g, sat_fat_g, sodium_mg, brand, barcode, source)
  values ('Chicken Biryani','prepared_dish','g',160,10.6,17,5.1,0,0,0,0,null,null,'curated')
  on conflict do nothing returning id
)
insert into public.food_servings (food_id, label, grams, is_default, source, seq)
select f.id, v.label, v.grams, v.is_default, v.source, v.seq
from f cross join (values ('1 bowl',312,true,'curated',0), ('100 g',100,false,'curated',1)) as v(label, grams, is_default, source, seq);

with f as (
  insert into public.foods
    (name, food_category, base_unit, kcal, protein_g, carb_g, fat_g, fiber_g, sugar_g, sat_fat_g, sodium_mg, brand, barcode, source)
  values ('Chicken Breast (cooked)','protein','g',165,31,0,3.6,0,0,1,74,null,null,'usda')
  on conflict do nothing returning id
)
insert into public.food_servings (food_id, label, grams, is_default, source, seq)
select f.id, v.label, v.grams, v.is_default, v.source, v.seq
from f cross join (values ('1 cup, chopped or diced',140,true,'usda',1), ('1 unit (yield from 1 lb ready-to-cook chicken)',52,false,'usda',2), ('0.5 breast, bone and skin removed',86,false,'usda',3), ('100 g',100,false,'usda',999)) as v(label, grams, is_default, source, seq);

with f as (
  insert into public.foods
    (name, food_category, base_unit, kcal, protein_g, carb_g, fat_g, fiber_g, sugar_g, sat_fat_g, sodium_mg, brand, barcode, source)
  values ('Chicken Thigh (cooked)','protein','g',179,24.8,0,8.2,0,0,2.3,106,null,null,'usda')
  on conflict do nothing returning id
)
insert into public.food_servings (food_id, label, grams, is_default, source, seq)
select f.id, v.label, v.grams, v.is_default, v.source, v.seq
from f cross join (values ('3 oz',85,true,'usda',1), ('1 thigh without skin',116,false,'usda',2), ('1 thigh with skin',137,false,'usda',3), ('100 g',100,false,'usda',999)) as v(label, grams, is_default, source, seq);

with f as (
  insert into public.foods
    (name, food_category, base_unit, kcal, protein_g, carb_g, fat_g, fiber_g, sugar_g, sat_fat_g, sodium_mg, brand, barcode, source)
  values ('Chickpeas (cooked)','legume','g',164,8.9,27.4,2.6,7.6,4.8,0.3,7,null,null,'usda')
  on conflict do nothing returning id
)
insert into public.food_servings (food_id, label, grams, is_default, source, seq)
select f.id, v.label, v.grams, v.is_default, v.source, v.seq
from f cross join (values ('1 cup',164,true,'usda',1), ('100 g',100,false,'usda',999)) as v(label, grams, is_default, source, seq);

with f as (
  insert into public.foods
    (name, food_category, base_unit, kcal, protein_g, carb_g, fat_g, fiber_g, sugar_g, sat_fat_g, sodium_mg, brand, barcode, source)
  values ('Cottage Cheese (lowfat)','dairy','g',81,10.5,4.8,2.3,0,4,1.2,308,null,null,'usda')
  on conflict do nothing returning id
)
insert into public.food_servings (food_id, label, grams, is_default, source, seq)
select f.id, v.label, v.grams, v.is_default, v.source, v.seq
from f cross join (values ('4 oz',113,true,'usda',1), ('1 cup (not packed)',226,false,'usda',2), ('100 g',100,false,'usda',999)) as v(label, grams, is_default, source, seq);

with f as (
  insert into public.foods
    (name, food_category, base_unit, kcal, protein_g, carb_g, fat_g, fiber_g, sugar_g, sat_fat_g, sodium_mg, brand, barcode, source)
  values ('Dal Tadka','prepared_dish','g',134,5.7,16.5,4.4,0,0,0,0,null,null,'curated')
  on conflict do nothing returning id
)
insert into public.food_servings (food_id, label, grams, is_default, source, seq)
select f.id, v.label, v.grams, v.is_default, v.source, v.seq
from f cross join (values ('1 bowl',198,true,'curated',0), ('100 g',100,false,'curated',1)) as v(label, grams, is_default, source, seq);

with f as (
  insert into public.foods
    (name, food_category, base_unit, kcal, protein_g, carb_g, fat_g, fiber_g, sugar_g, sat_fat_g, sodium_mg, brand, barcode, source)
  values ('Egg (whole, raw)','protein','g',143,12.6,0.7,9.5,0,0.4,3.1,142,null,null,'usda')
  on conflict do nothing returning id
)
insert into public.food_servings (food_id, label, grams, is_default, source, seq)
select f.id, v.label, v.grams, v.is_default, v.source, v.seq
from f cross join (values ('1 large',50,true,'usda',1), ('1 extra large',56,false,'usda',2), ('1 jumbo',63,false,'usda',3), ('1 cup (4.86 large eggs)',243,false,'usda',5), ('1 medium',44,false,'usda',6), ('1 small',38,false,'usda',7), ('100 g',100,false,'usda',999)) as v(label, grams, is_default, source, seq);

with f as (
  insert into public.foods
    (name, food_category, base_unit, kcal, protein_g, carb_g, fat_g, fiber_g, sugar_g, sat_fat_g, sodium_mg, brand, barcode, source)
  values ('Greek Yogurt (plain, nonfat)','dairy','g',59,10.2,3.6,0.4,0,3.2,0.1,36,null,null,'usda')
  on conflict do nothing returning id
)
insert into public.food_servings (food_id, label, grams, is_default, source, seq)
select f.id, v.label, v.grams, v.is_default, v.source, v.seq
from f cross join (values ('1 container',170,true,'usda',1), ('100 g',100,false,'usda',999)) as v(label, grams, is_default, source, seq);

with f as (
  insert into public.foods
    (name, food_category, base_unit, kcal, protein_g, carb_g, fat_g, fiber_g, sugar_g, sat_fat_g, sodium_mg, brand, barcode, source)
  values ('Kidney Beans (cooked)','legume','g',127,8.7,22.8,0.5,7.4,0.3,0.1,2,null,null,'usda')
  on conflict do nothing returning id
)
insert into public.food_servings (food_id, label, grams, is_default, source, seq)
select f.id, v.label, v.grams, v.is_default, v.source, v.seq
from f cross join (values ('1 cup',177,true,'usda',1), ('1 tbsp',11,false,'usda',2), ('100 g',100,false,'usda',999)) as v(label, grams, is_default, source, seq);

with f as (
  insert into public.foods
    (name, food_category, base_unit, kcal, protein_g, carb_g, fat_g, fiber_g, sugar_g, sat_fat_g, sodium_mg, brand, barcode, source)
  values ('Lentils (cooked)','legume','g',116,9,20.1,0.4,7.9,1.8,0.1,2,null,null,'usda')
  on conflict do nothing returning id
)
insert into public.food_servings (food_id, label, grams, is_default, source, seq)
select f.id, v.label, v.grams, v.is_default, v.source, v.seq
from f cross join (values ('1 cup',198,true,'usda',1), ('1 tbsp',12.3,false,'usda',2), ('100 g',100,false,'usda',999)) as v(label, grams, is_default, source, seq);

with f as (
  insert into public.foods
    (name, food_category, base_unit, kcal, protein_g, carb_g, fat_g, fiber_g, sugar_g, sat_fat_g, sodium_mg, brand, barcode, source)
  values ('Oats (dry)','grain','g',379,13.2,67.7,6.5,10.1,1,1.1,6,null,null,'usda')
  on conflict do nothing returning id
)
insert into public.food_servings (food_id, label, grams, is_default, source, seq)
select f.id, v.label, v.grams, v.is_default, v.source, v.seq
from f cross join (values ('1 cup',81,true,'usda',1), ('0.3 cup',27,false,'usda',2), ('100 g',100,false,'usda',999)) as v(label, grams, is_default, source, seq);

with f as (
  insert into public.foods
    (name, food_category, base_unit, kcal, protein_g, carb_g, fat_g, fiber_g, sugar_g, sat_fat_g, sodium_mg, brand, barcode, source)
  values ('Olive Oil','fat_oil','g',884,0,0,100,0,0,13.8,2,null,null,'usda')
  on conflict do nothing returning id
)
insert into public.food_servings (food_id, label, grams, is_default, source, seq)
select f.id, v.label, v.grams, v.is_default, v.source, v.seq
from f cross join (values ('1 tablespoon',13.5,true,'usda',1), ('1 cup',216,false,'usda',2), ('1 tsp',4.5,false,'usda',3), ('100 g',100,false,'usda',999)) as v(label, grams, is_default, source, seq);

with f as (
  insert into public.foods
    (name, food_category, base_unit, kcal, protein_g, carb_g, fat_g, fiber_g, sugar_g, sat_fat_g, sodium_mg, brand, barcode, source)
  values ('Paneer Butter Masala','prepared_dish','g',173,7.8,3.3,14.1,0,0,0,0,null,null,'curated')
  on conflict do nothing returning id
)
insert into public.food_servings (food_id, label, grams, is_default, source, seq)
select f.id, v.label, v.grams, v.is_default, v.source, v.seq
from f cross join (values ('1 bowl',205,true,'curated',0), ('100 g',100,false,'curated',1)) as v(label, grams, is_default, source, seq);

with f as (
  insert into public.foods
    (name, food_category, base_unit, kcal, protein_g, carb_g, fat_g, fiber_g, sugar_g, sat_fat_g, sodium_mg, brand, barcode, source)
  values ('Peanut Butter','nuts_seeds','g',598,22.2,22.3,51.4,5,10.5,10.3,426,null,null,'usda')
  on conflict do nothing returning id
)
insert into public.food_servings (food_id, label, grams, is_default, source, seq)
select f.id, v.label, v.grams, v.is_default, v.source, v.seq
from f cross join (values ('2 tbsp',32,true,'usda',1), ('1 cup',258,false,'usda',2), ('100 g',100,false,'usda',999)) as v(label, grams, is_default, source, seq);

with f as (
  insert into public.foods
    (name, food_category, base_unit, kcal, protein_g, carb_g, fat_g, fiber_g, sugar_g, sat_fat_g, sodium_mg, brand, barcode, source)
  values ('Peanuts','nuts_seeds','g',587,24.4,21.3,49.7,8.4,4.9,7.7,6,null,null,'usda')
  on conflict do nothing returning id
)
insert into public.food_servings (food_id, label, grams, is_default, source, seq)
select f.id, v.label, v.grams, v.is_default, v.source, v.seq
from f cross join (values ('1 cup',146,true,'usda',1), ('1 oz',28.35,false,'usda',2), ('1 peanut',1,false,'usda',3), ('100 g',100,false,'usda',999)) as v(label, grams, is_default, source, seq);

with f as (
  insert into public.foods
    (name, food_category, base_unit, kcal, protein_g, carb_g, fat_g, fiber_g, sugar_g, sat_fat_g, sodium_mg, brand, barcode, source)
  values ('Potato (boiled)','vegetable','g',87,1.9,20.1,0.1,1.8,0.9,0,4,null,null,'usda')
  on conflict do nothing returning id
)
insert into public.food_servings (food_id, label, grams, is_default, source, seq)
select f.id, v.label, v.grams, v.is_default, v.source, v.seq
from f cross join (values ('0.5 cup',78,true,'usda',1), ('1 potato (2-1/2" dia, sphere)',136,false,'usda',2), ('100 g',100,false,'usda',999)) as v(label, grams, is_default, source, seq);

with f as (
  insert into public.foods
    (name, food_category, base_unit, kcal, protein_g, carb_g, fat_g, fiber_g, sugar_g, sat_fat_g, sodium_mg, brand, barcode, source)
  values ('Rajma Chawal','prepared_dish','g',132,4.6,21.8,2.8,0,0,0,0,null,null,'curated')
  on conflict do nothing returning id
)
insert into public.food_servings (food_id, label, grams, is_default, source, seq)
select f.id, v.label, v.grams, v.is_default, v.source, v.seq
from f cross join (values ('1 bowl',328,true,'curated',0), ('100 g',100,false,'curated',1)) as v(label, grams, is_default, source, seq);

with f as (
  insert into public.foods
    (name, food_category, base_unit, kcal, protein_g, carb_g, fat_g, fiber_g, sugar_g, sat_fat_g, sodium_mg, brand, barcode, source)
  values ('Salmon (cooked)','protein','g',206,22.1,0,12.4,0,0,2.4,61,null,null,'usda')
  on conflict do nothing returning id
)
insert into public.food_servings (food_id, label, grams, is_default, source, seq)
select f.id, v.label, v.grams, v.is_default, v.source, v.seq
from f cross join (values ('3 oz',85,true,'usda',1), ('0.5 fillet',178,false,'usda',2), ('100 g',100,false,'usda',999)) as v(label, grams, is_default, source, seq);

with f as (
  insert into public.foods
    (name, food_category, base_unit, kcal, protein_g, carb_g, fat_g, fiber_g, sugar_g, sat_fat_g, sodium_mg, brand, barcode, source)
  values ('Shrimp (cooked)','protein','g',99,24,0.2,0.3,0,0,0.1,111,null,null,'usda')
  on conflict do nothing returning id
)
insert into public.food_servings (food_id, label, grams, is_default, source, seq)
select f.id, v.label, v.grams, v.is_default, v.source, v.seq
from f cross join (values ('3 oz',85,true,'usda',1), ('100 g',100,false,'usda',999)) as v(label, grams, is_default, source, seq);

with f as (
  insert into public.foods
    (name, food_category, base_unit, kcal, protein_g, carb_g, fat_g, fiber_g, sugar_g, sat_fat_g, sodium_mg, brand, barcode, source)
  values ('Spinach (raw)','vegetable','g',23,2.9,3.6,0.4,2.2,0.4,0.1,79,null,null,'usda')
  on conflict do nothing returning id
)
insert into public.food_servings (food_id, label, grams, is_default, source, seq)
select f.id, v.label, v.grams, v.is_default, v.source, v.seq
from f cross join (values ('1 cup',30,true,'usda',1), ('1 bunch',340,false,'usda',2), ('1 leaf',10,false,'usda',3), ('1 package (10 oz)',284,false,'usda',4), ('100 g',100,false,'usda',999)) as v(label, grams, is_default, source, seq);

with f as (
  insert into public.foods
    (name, food_category, base_unit, kcal, protein_g, carb_g, fat_g, fiber_g, sugar_g, sat_fat_g, sodium_mg, brand, barcode, source)
  values ('Sweet Potato (cooked)','vegetable','g',90,2,20.7,0.2,3.3,6.5,0.1,36,null,null,'usda')
  on conflict do nothing returning id
)
insert into public.food_servings (food_id, label, grams, is_default, source, seq)
select f.id, v.label, v.grams, v.is_default, v.source, v.seq
from f cross join (values ('1 cup',200,true,'usda',1), ('1 large',180,false,'usda',2), ('1 medium (2" dia, 5" long, raw)',114,false,'usda',3), ('1 small',60,false,'usda',4), ('100 g',100,false,'usda',999)) as v(label, grams, is_default, source, seq);

with f as (
  insert into public.foods
    (name, food_category, base_unit, kcal, protein_g, carb_g, fat_g, fiber_g, sugar_g, sat_fat_g, sodium_mg, brand, barcode, source)
  values ('Tofu (firm)','protein','g',78,9,2.9,4.2,0.9,0.6,0.8,12,null,null,'usda')
  on conflict do nothing returning id
)
insert into public.food_servings (food_id, label, grams, is_default, source, seq)
select f.id, v.label, v.grams, v.is_default, v.source, v.seq
from f cross join (values ('0.5 cup',126,true,'usda',1), ('0.3 block',81,false,'usda',2), ('0.2 block',91,false,'usda',3), ('100 g',100,false,'usda',999)) as v(label, grams, is_default, source, seq);

with f as (
  insert into public.foods
    (name, food_category, base_unit, kcal, protein_g, carb_g, fat_g, fiber_g, sugar_g, sat_fat_g, sodium_mg, brand, barcode, source)
  values ('Tuna (canned in water)','protein','g',86,19.4,0,1,0,0,0.2,247,null,null,'usda')
  on conflict do nothing returning id
)
insert into public.food_servings (food_id, label, grams, is_default, source, seq)
select f.id, v.label, v.grams, v.is_default, v.source, v.seq
from f cross join (values ('1 oz',28.35,true,'usda',1), ('3 oz',85,false,'usda',2), ('1 can',165,false,'usda',3), ('1 cup, solid or chunks',154,false,'usda',4), ('1 can (12.5 oz), drained',315,false,'usda',5), ('100 g',100,false,'usda',999)) as v(label, grams, is_default, source, seq);

with f as (
  insert into public.foods
    (name, food_category, base_unit, kcal, protein_g, carb_g, fat_g, fiber_g, sugar_g, sat_fat_g, sodium_mg, brand, barcode, source)
  values ('Walnuts','nuts_seeds','g',654,15.2,13.7,65.2,6.7,2.6,6.1,2,null,null,'usda')
  on conflict do nothing returning id
)
insert into public.food_servings (food_id, label, grams, is_default, source, seq)
select f.id, v.label, v.grams, v.is_default, v.source, v.seq
from f cross join (values ('1 cup, chopped',117,true,'usda',1), ('1 cup, ground',80,false,'usda',2), ('1 cup, in shell, edible yield (7 nuts)',28,false,'usda',3), ('1 cup shelled (50 halves)',100,false,'usda',4), ('1 cup pieces or chips',120,false,'usda',5), ('1 oz (14 halves)',28.35,false,'usda',6), ('100 g',100,false,'usda',999)) as v(label, grams, is_default, source, seq);

with f as (
  insert into public.foods
    (name, food_category, base_unit, kcal, protein_g, carb_g, fat_g, fiber_g, sugar_g, sat_fat_g, sodium_mg, brand, barcode, source)
  values ('White Rice (cooked)','grain','g',130,2.7,28.2,0.3,0.4,0.1,0.1,382,null,null,'usda')
  on conflict do nothing returning id
)
insert into public.food_servings (food_id, label, grams, is_default, source, seq)
select f.id, v.label, v.grams, v.is_default, v.source, v.seq
from f cross join (values ('1 cup',158,true,'usda',1), ('100 g',100,false,'usda',999)) as v(label, grams, is_default, source, seq);

with f as (
  insert into public.foods
    (name, food_category, base_unit, kcal, protein_g, carb_g, fat_g, fiber_g, sugar_g, sat_fat_g, sodium_mg, brand, barcode, source)
  values ('Whole Milk','dairy','g',61,3.2,4.8,3.3,0,5.1,1.9,43,null,null,'usda')
  on conflict do nothing returning id
)
insert into public.food_servings (food_id, label, grams, is_default, source, seq)
select f.id, v.label, v.grams, v.is_default, v.source, v.seq
from f cross join (values ('1 cup',244,true,'usda',1), ('1 tbsp',15,false,'usda',2), ('1 fl oz',30.5,false,'usda',3), ('1 quart',976,false,'usda',4), ('100 g',100,false,'usda',999)) as v(label, grams, is_default, source, seq);

with f as (
  insert into public.foods
    (name, food_category, base_unit, kcal, protein_g, carb_g, fat_g, fiber_g, sugar_g, sat_fat_g, sodium_mg, brand, barcode, source)
  values ('Whole Wheat Bread','grain','g',252,12.5,42.7,3.5,6,4.3,0.7,455,null,null,'usda')
  on conflict do nothing returning id
)
insert into public.food_servings (food_id, label, grams, is_default, source, seq)
select f.id, v.label, v.grams, v.is_default, v.source, v.seq
from f cross join (values ('1 slice',32,true,'usda',1), ('1 oz',28.35,false,'usda',2), ('100 g',100,false,'usda',999)) as v(label, grams, is_default, source, seq);

with f as (
  insert into public.foods
    (name, food_category, base_unit, kcal, protein_g, carb_g, fat_g, fiber_g, sugar_g, sat_fat_g, sodium_mg, brand, barcode, source)
  values ('Whole Wheat Flour (atta)','grain','g',332,9.6,74.5,2,13.1,1,0.4,3,null,null,'usda')
  on conflict do nothing returning id
)
insert into public.food_servings (food_id, label, grams, is_default, source, seq)
select f.id, v.label, v.grams, v.is_default, v.source, v.seq
from f cross join (values ('100 g',100,true,'usda',999)) as v(label, grams, is_default, source, seq);
