/**
 * Curated Indian-dish ingest (compute-don't-copy) -> the SERVER catalog seed.
 *
 * Reads DISHES from indian-dishes.ts (each an ingredient breakdown), computes each
 * dish's per-100 g macros from the clean RAW_INGREDIENTS base, and emits an
 * enriching-insert seed for Supabase `foods` + `food_servings`, tagged source
 * 'curated' (our own work product; legally clean vs IFCT/INDB — see README).
 *
 * Segregation-safe like ingest-off: DO NOTHING on a name conflict (never clobber a
 * USDA/OFF/curated-staple row that already owns the name), and dish servings attach
 * only to curated rows. Extended nutrients beyond fiber (sugar/sat_fat/sodium) are
 * left NULL — we can't attribute them reliably per-ingredient, and missing != 0.
 *
 * Run:    npx tsx scripts/diet-catalog/ingest-dishes.ts
 * Output: supabase/seed/curated_dishes.generated.sql
 * Apply:  bash scripts/load-usda-seed.sh supabase/seed/curated_dishes.generated.sql
 * Reversible: delete from public.foods where 'curated' = any(sources) and food_category in ('prepared_dish','sweet');
 */

import fs from 'node:fs';
import path from 'node:path';
import { DISHES, computeDish } from './indian-dishes';

const REPO_ROOT = path.resolve(__dirname, '../..');
const CHUNK = 200;
const round1 = (n: number) => Math.round(n * 10) / 10;

interface Row {
  name: string;
  food_category: string;
  kcal: number; protein_g: number; carb_g: number; fat_g: number; fiber_g: number;
  servings: { label: string; grams: number; is_default: boolean; seq: number }[];
}

function buildRows(): Row[] {
  const rows: Row[] = [];
  for (const dish of DISHES) {
    const total = computeDish(dish);
    const grams = dish.ingredients.reduce((s, c) => s + c.grams, 0);
    if (!(grams > 0)) continue;
    const per100 = (v: number) => (v / grams) * 100;
    rows.push({
      name: dish.name,
      food_category: dish.food_category,
      kcal: Math.round(per100(total.kcal)),
      protein_g: round1(per100(total.protein_g)),
      carb_g: round1(per100(total.carb_g)),
      fat_g: round1(per100(total.fat_g)),
      fiber_g: round1(per100(total.fiber_g)),
      servings: [
        { label: dish.serving ?? '1 serving', grams: Math.round(grams), is_default: true, seq: 0 },
        { label: '100 g', grams: 100, is_default: false, seq: 999 },
      ],
    });
  }
  return rows.sort((a, b) => a.name.localeCompare(b.name));
}

function esc(s: string) { return s.replace(/'/g, "''"); }

function emit(rows: Row[]) {
  let sql = `-- GENERATED by scripts/diet-catalog/ingest-dishes.ts — do not edit by hand.
-- Curated Indian dishes (compute-don't-copy): ${rows.length} foods, source='curated'.
-- Apply as SERVICE ROLE (created_by stays null = global). DO NOTHING on name conflict.
-- Reversible: delete from public.foods where 'curated'=any(sources) and food_category in ('prepared_dish','sweet');
`;
  for (let i = 0; i < rows.length; i += CHUNK) {
    const batch = rows.slice(i, i + CHUNK);
    const foodValues = batch.map((r) =>
      `('${esc(r.name)}','${r.food_category}','g',${r.kcal},${r.protein_g},${r.carb_g},${r.fat_g},${r.fiber_g},'curated',array['curated'],'india')`,
    ).join(',\n');
    sql += `\ninsert into public.foods
  (name, food_category, base_unit, kcal, protein_g, carb_g, fat_g, fiber_g, source, sources, region)
values
${foodValues}
on conflict (lower(name)) where created_by is null do nothing;
`;
    const servValues = batch.flatMap((r) =>
      r.servings.map((s) => `('${esc(r.name)}','${esc(s.label)}',${s.grams},${s.seq})`),
    ).join(',\n');
    const batchNames = batch.map((r) => `'${esc(r.name.toLowerCase())}'`).join(', ');
    const defaultPairs = batch.map((r) => {
      const def = r.servings.find((s) => s.is_default) ?? r.servings[0];
      return `('${esc(r.name)}','${esc(def.label)}')`;
    }).join(',\n');
    // servings attach ONLY to curated rows (a dish name we just inserted); the guard
    // keeps a dish serving off any pre-existing USDA/OFF row that shares the name.
    sql += `\ninsert into public.food_servings (food_id, label, grams, is_default, source, seq)
select f.id, v.label, v.grams, false, 'curated', v.seq
from (values
${servValues}
) as v(food_name, label, grams, seq)
join public.foods f on lower(f.name) = lower(v.food_name) and f.created_by is null and 'curated' = any(f.sources)
on conflict (food_id, lower(label)) do update set grams = excluded.grams, seq = excluded.seq;
`;
    sql += `\nupdate public.food_servings s set is_default = false
from public.foods f
where s.food_id = f.id and f.created_by is null and 'curated' = any(f.sources) and s.is_default
  and lower(f.name) in (${batchNames});

update public.food_servings s set is_default = true
from (values
${defaultPairs}
) as d(food_name, label)
join public.foods f on lower(f.name) = lower(d.food_name) and f.created_by is null and 'curated' = any(f.sources)
where s.food_id = f.id and lower(s.label) = lower(d.label);
`;
  }
  const destDir = path.join(REPO_ROOT, 'supabase/seed');
  fs.mkdirSync(destDir, { recursive: true });
  const dest = path.join(destDir, 'curated_dishes.generated.sql');
  fs.writeFileSync(dest, sql);
  console.log(`[dishes] -> ${path.relative(REPO_ROOT, dest)} (${rows.length} dishes, ${Math.ceil(rows.length / CHUNK)} batch)`);
}

function main() {
  const rows = buildRows();
  // sanity: flag any dish with an implausible computed macro so bad breakdowns surface
  for (const r of rows) {
    if (r.kcal <= 0 || r.kcal > 600 || r.protein_g > 50 || r.carb_g > 90 || r.fat_g > 60) {
      console.warn(`  [check] ${r.name}: ${r.kcal}kcal P${r.protein_g} C${r.carb_g} F${r.fat_g} — verify breakdown`);
    }
  }
  console.log(`[dishes] computed ${rows.length} dishes`);
  emit(rows);
  console.log('[done] curated dish build complete.');
}

main();
